sudo: required

language: ruby

services:
  - docker

addons:
  apt:
    packages:
    - make

before_install:
  - make build

deploy:
  - echo "$DOCKER_HUB_PASSWORD" | docker login -u blockloop --password-stdin
  - make push

