sudo: required
services:
  - docker

env:
  global:
    - DOCKER_USER=blockloop

addons:
  apt:
    packages:
    - make

script:
  - make build

after_script:
  - docker images

before_deploy:
  - docker login -u "$DOCKER_USER" -p "$DOCKER_HUB_PASSWORD"

deploy:
  provider: script
  script: make push
  on:
    branch: master
