sudo: required
services:
  - docker

env:
  global:
    - DOCKER_USER=blockloop

addons:
  apt:
    packages:
    - make

script:
  - docker pull blockloop/ghost
  - make build

after_script:
  - docker images

before_deploy:
  - echo "$DOCKER_HUB_PASSWORD" | docker login -u "$DOCKER_USER" --password-stdin

deploy:
  provider: script
  script: make push
  on:
    branch: master
